### ISSUE TITLE
cedrus on h616, 6.11.3 kernel, vainfo reports empty list of "Supported profile and entrypoints"

### ISSUE THREAD

**Issue by warpme** [mxsrc/libva-v4l2#1]
Hi,
This is _very_ interesting project!
I want to give it try on mine appliance (MiniMyth2)
With 6.11.3 kernel i have well working v4l2_request on series of socs (h6/h313/h616/h618/rk3328/rk3399/rk3566/rk3588)
I'm testing current master of libva-v4l2 on h618 tvbox which perfectly plays hw accelerated h264, hevc, etc on mythtv and kodi
basic logs about what box provides (v4l2_request, drm, etc): http://termbin.com/kdx2

running vainfo (with `export LIBVA_DRIVER_NAME=v4l2`) with current master of libva-v4l2 gives me:
    

```
root@myth-frontend-02001a758ab4:~ # vainfo
Trying display: x11
error: can't connect to X server!
Trying display: drm
libva info: VA-API version 1.22.0
libva info: User environment variable requested driver 'v4l2'
libva info: Trying to open /usr/lib/v4l2_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.22 (libva 2.22.0)
vainfo: Driver version: v4l2
vainfo: Supported profile and entrypoints
root@myth-frontend-02001a758ab4:~ #
```

maybe you have some hints why va reports no any profiles nor entrypoints?

note: minimyth2 has no systemd. For udev i'm using eudev 3.2.14 which offers udev251 api. 
libva-v4l2 requires udev 252 api.
can udev 251 api level be root cause of empty list of "Supported profile and entrypoints"?

**Comment by mxsrc** [comment]
Hi, thanks for your interest in the project! The version requirement for `libudev` is a conservative estimate, it's the version I worked with, as far as I can tell it should work with lower versions as well. You can circumvent this by using `LIBVA_V4L2_{VIDEO,MEDIA}_PATH` to explicitly set the devices to be used instead of relying on auto-lookup. The correct devices can be determined using `v4l2-ctl` and `media-ctl` respectively which should be shipped as part of `v4l2-utils`.

If forcing the device doesn't solve this the root issue is a different one, but maybe it's the simpler one :)

**Comment by warpme** [comment]
Indeed - I already tried to hint driver with video/media nodes:

```
BusyBox v1.36.1 (2024-10-01 23:21:36 CEST) built-in shell (ash)

root@myth-frontend-02001a758ab4:~ # ls -1 /dev/media*
/dev/media0
root@myth-frontend-02001a758ab4:~ # ls -1 /dev/video*
/dev/video0
root@myth-frontend-02001a758ab4:~ # export LIBVA_V4L2_VIDEO_PATH=/dev/video0 LIBVA_V4L2_MEDIA_PATH=/dev/media0
root@myth-frontend-02001a758ab4:~ # export LIBVA_DRIVER_NAME=v4l2
root@myth-frontend-02001a758ab4:~ # vainfo
Trying display: x11
error: can't connect to X server!
Trying display: drm
libva info: VA-API version 1.22.0
libva info: User environment variable requested driver 'v4l2'
libva info: Trying to open /usr/lib/v4l2_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: Overriding V4L2 device with /dev/video0 & /dev/media0.
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Aborted
root@myth-frontend-02001a758ab4:~ #
```

**Comment by mxsrc** [comment]
Thanks for the input! I created a PR (#2) that should provide support for the single-planar V4L2 variant as well. It should at least make the library pick up on your device and expose the supported entrypoints (MPEG2, H264, and VP8. HEVC is not supported right now since I couldn't test that).

Your `vainfo` call when using the environment variables indicates another problem though, exceptions should only be used internally and not be propagated to the user. Could you run `vainfo` in a debugger and post the backtrace to show where the error is thrown?

**Comment by mxsrc** [comment]
Okay, I will have to look into this in more detail. The error that occurs when starting Kodi seems similar to one I encountered while looking into stateful decoders. In that case, the VA-API client requests more buffers/surfaces, than V4L2 can offer. At the moment, there's a 1:1 correspondence between the two, I am looking into decoupling this but I'd like to confirm this is actually the cause here. The error mythtv gives you seems to be a different one. Can you compile a debug build of `libva-v4l2` (`meson setup --buildtype=debug build`) to give some more details on the backtrace?

In any case, I'm afraid this will require some debugging. I am trying to acquire an SBC that uses an Allwinner SoC so I can look into this more directly, that may take a few days though.

**Comment by mxsrc** [comment]
I have fixed a few issues and believe I have uncovered the problem with H264 decoding, `cedrus` uses slice-based decoding and the existing code only works frame-based. Could you give #3 a try?

**Comment by warpme** [comment]
Sure :)
I compiled https://github.com/mxsrc/libva-v4l2/tree/h264-slice-based with debug profile.
Unfortunately starting kodi gives me:

```
Kodi cmd.line:/usr/lib/kodi/kodi-gbm
libva info: VA-API version 1.22.0
libva error: vaGetDriverNames() failed with operation failed
libva info: User environment variable requested driver 'v4l2'
libva info: Trying to open /usr/lib/v4l2_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
/home/piotro/minimyth2-aarch64-next/images/build/usr/lib/gcc/aarch64-minimyth-linux-gnu/14.2.0/include/c++/optional:482: constexpr const _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() const [with _Tp = std::reference_wrapper<const V4L2M2MDevice::Buffer>; _Dp = std::_Optional_base<std::reference_wrapper<const V4L2M2MDevice::Buffer>, true, true>]: Assertion 'this->_M_is_engaged()' failed.
Aborted
root@myth-frontend-02035e98a1bb:~ #
```

mythtv playback gives segfault 

trace is:https://gist.github.com/warpme/27fd33480fa0f67d76646b1585fee01b

ps: i compiled with debug symbols only libva-v4l2 as mythtv with debug symbols needs something like 5G ram to catch segfault under gdb.
System under test was allwinner h6 with 2G.
If you need gdb trace also from mythtv - i can recompile and run test on 8G ram rk3588 board (3588 also has h264 v4l2_request working via on-chip hantro g1 decoder). Pls just let me know...

**Comment by mxsrc** [comment]
As the original issue seems solved I've merged the two other PRs. As for MythTV failing, after looking into the code I believe to understand what's causing it.

When creating the libVA driver context, MythTV seems to have trust issues with the advertised memory formats and tries to test them by creating a surface and exporting a handle to it. Unfortunately, with libva-v4l2 that mistrust is justified: The V4L2-M2M buffers corresponding to the libVA surfaces are only created after the decode context, which communicates the exact surface format. So when MythTV is probing the surfaces, the backing buffer doesn't exist yet and hence it fails. 

I'll try to work around this by spoofing a buffer outside of V4L2. This might be a bit tricky though and I'll probably have to look into a local MythTV instance for testing purposes.

**Comment by warpme** [comment]
Pls let me know if there is anything i can provide to help...
 (i.e. Archlinux build of MythTV frontend for your board for MiniArch Archlinux ARM)

**Comment by mxsrc** [comment]
Actually that would be really helpful. I've noticed you already have images for ROCK4s which might already work for me. The issue seems to be MythTV specific, so using that should work just fine as well. I just have the 4+, the images appear to be for 4SE and 4B only, do you reckon either would work on my board?

**Comment by warpme** [comment]
Ok - prepared small how-to about installing MythTV on Miniarch: https://github.com/warpme/miniarch/wiki/Installing-and-Setup-MythTV-on-MiniArch

Both mythtv arch package and miniarch kernel have full support of v4l2_request for mpeg2/vp8/vp9/h264/hevc.
Kernel ABI is also "conformant" with Kodi (assuming ffmpeg used by Kodi has v4l2_requrest & v4l2_drmprime patches applied) (you may look on https://github.com/warpme/minimyth2/tree/master/script/lib ffmpeg dirs. Thise ffmpegs are working well with Kodi I have in https://github.com/warpme/minimyth2/tree/master/script/mediaplayers/kodi) 

Currently miniarch don't offers dedicated image for rock4+ (as I don't have this board to test) - but you may 4b or 4se. I think they are quite close :-)

 Good luck!

**Comment by mxsrc** [comment]
I didn't find the time recently to look into this, but I have now set up myth TV on my Rock 4. The instructions were really helpful, the whole thing went (mostly) quite smoothly. I didn't yet check the issue itself, but now that the system is running I'll look into that soon.

**Comment by aaronhtelevic** [comment]
Hi,
I have a similar problem with coda960 on imx6.
* The VPU is successfully detected with v4l2-ctl.
* vainfo gives some output, but also doesn't list the formats

Any clue what I can do?

Goal: I want to run qtwebengine with video decoding

```shell
root@imx6:~# cat /sys/class/video4linux/video3/name
coda-video-decoder
root@imx6:~# v4l2-ctl -d /dev/video3  -D --list-formats-ext --list-formats-out-ext
Driver Info:
        Driver name      : coda
        Card type        : CODA960
        Bus info         : platform:coda
        Driver version   : 6.1.92
        Capabilities     : 0x84208000
                Video Memory-to-Memory
                Streaming
                Extended Pix Format
                Device Capabilities
        Device Caps      : 0x04208000
                Video Memory-to-Memory
                Streaming
                Extended Pix Format
ioctl: VIDIOC_ENUM_FMT
        Type: Video Capture

        [0]: 'NV12' (Y/UV 4:2:0)
        [1]: 'YU12' (Planar YUV 4:2:0)
        [2]: 'YV12' (Planar YVU 4:2:0)
        [3]: 'YUYV' (YUYV 4:2:2)
ioctl: VIDIOC_ENUM_FMT
        Type: Video Output

        [0]: 'H264' (H.264, compressed)
        [1]: 'MPG2' (MPEG-2 ES, compressed)
        [2]: 'MPG4' (MPEG-4 Part 2 ES, compressed)
root@imx6:~# vainfo
Trying display: wayland
Trying display: drm
libva info: VA-API version 1.20.0
libva info: User environment variable requested driver 'v4l2'
libva info: Trying to open /usr/lib/dri/v4l2_drv_video.so
libva info: Found init function __vaDriverInit_1_20
libva info: Overriding V4L2 device with /dev/video3 & .
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.20 (libva 2.20.1)
vainfo: Driver version: v4l2
vainfo: Supported profile and entrypoints
```

**Comment by valpackett** [comment]
The list is also empty with Qualcomm's iris decoder (x1e80100, Linux 6.16.0-rc4-next-20250704):

```
❯ v4l2-ctl -d /dev/video0  -D --list-formats-ext --list-formats-out-ext
Driver Info:
	Driver name      : iris_driver
	Card type        : Iris Decoder
	Bus info         : platform:aa00000.video-codec
	Driver version   : 6.16.0
	Capabilities     : 0x84204000
		Video Memory-to-Memory Multiplanar
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x04204000
		Video Memory-to-Memory Multiplanar
		Streaming
		Extended Pix Format
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture Multiplanar

	[0]: 'NV12' (Y/UV 4:2:0)
		Size: Stepwise 96x96 - 8192x8192 with step 1/1
ioctl: VIDIOC_ENUM_FMT
	Type: Video Output Multiplanar

	[0]: 'H264' (H.264, compressed, dyn-resolution)
		Size: Stepwise 96x96 - 8192x8192 with step 1/1
	[1]: 'HEVC' (HEVC, compressed, dyn-resolution)
	[2]: 'VP90' (VP9, compressed, dyn-resolution)

❯ LIBVA_DRIVERS_PATH=/usr/local/lib/dri LIBVA_DRIVER_NAME=v4l2 vainfo
Trying display: wayland
libva info: VA-API version 1.22.0
libva info: User environment variable requested driver 'v4l2'
libva info: Trying to open /usr/local/lib/dri/v4l2_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.22 (libva 2.22.0)
vainfo: Driver version: v4l2
vainfo: Supported profile and entrypoints
```

**Comment by yunsmall** [comment]
Hi, it's also empty with armbian in Amlogic s905x3, hk1box. How can I solve it?
```
armbian:libva-v4l2:% uname -a                                          <master>
Linux armbian 6.1.157-ophub #1 SMP Mon Oct 20 10:19:24 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux

armbian:~:% neofetch
        #####           yunsmall@armbian 
       #######          ---------------- 
       ##O#O##          OS: Armbian OS 25.11.0 noble aarch64 
       #######          Host: HK1 Box/Vontar X3 
     ###########        Kernel: 6.1.157-ophub 
    #############       Uptime: 2 hours 
   ###############      Packages: 1580 (dpkg) 
   ################     Shell: zsh 5.9 
  #################     Resolution: 720x576i 
#####################   DE: GNOME 46.0 
#####################   WM: Mutter 
  #################     WM Theme: Adwaita 
                        Theme: Yaru [GTK2/3] 
                        Icons: Yaru [GTK2/3] 
                        Terminal: gnome-terminal 
                        CPU: ARMv8 rev 0 (v8l) (4) @ 2.100GHz 
                        Memory: 2610MiB / 3776MiB 

armbian:libva-v4l2:% LIBVA_DRIVERS_PATH=./build/src LIBVA_DRIVER_NAME=v4l2 vainfo                                  
libva info: VA-API version 1.20.0
libva info: User environment variable requested driver 'v4l2'
libva info: Trying to open ./build/src/v4l2_drv_video.so
libva info: Found init function __vaDriverInit_1_20
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.20 (libva 2.12.0)
vainfo: Driver version: v4l2
vainfo: Supported profile and entrypoints

armbian:libva-v4l2:% v4l2-ctl --list-formats-ext --list-formats-out-ext -d /dev/video0 -D
Driver Info:
	Driver name      : meson-vdec
	Card type        : Amlogic Video Decoder
	Bus info         : platform:meson-vdec
	Driver version   : 6.1.157
	Capabilities     : 0x84204000
		Video Memory-to-Memory Multiplanar
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x04204000
		Video Memory-to-Memory Multiplanar
		Streaming
		Extended Pix Format
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture Multiplanar

	[0]: 'NM12' (Y/UV 4:2:0 (N-C))
ioctl: VIDIOC_ENUM_FMT
	Type: Video Output Multiplanar

	[0]: 'VP90' (VP9, compressed, dyn-resolution)
		Size: Continuous 256x144 - 3840x2160
	[1]: 'HEVC' (HEVC, compressed, dyn-resolution)
		Size: Continuous 256x144 - 3840x2160
	[2]: 'H264' (H.264, compressed, dyn-resolution)
		Size: Continuous 256x144 - 3840x2160
	[3]: 'MPG1' (MPEG-1 ES, compressed)
		Size: Continuous 256x144 - 1920x1080
	[4]: 'MPG2' (MPEG-2 ES, compressed)
		Size: Continuous 256x144 - 1920x1080
```

**Comment by marfrit** [comment]
I try to get vaapi -> v4l2_request -> (hantro, rkvdec) -> rk3399 (pinebook-pro) to work. However, mpv SIGABRTs with

```
Thread 1 (Thread 0xffff88ffe520 (LWP 2410)):
#0  0x0000ffffae92b1f4 in ?? () from /usr/lib/libc.so.6
#1  0x0000ffffae8d78d8 in raise () from /usr/lib/libc.so.6
#2  0x0000ffffae8c1c38 in abort () from /usr/lib/libc.so.6
#3  0x0000ffffaa9937a8 in std::__glibcxx_assert_fail (file=<optimized out>, line=<optimized out>, function=<optimized out>, condition=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/assert_fail.cc:41
#4  0x0000ffff883b6010 in std::optional<std::reference_wrapper<V4L2M2MDevice::Buffer const> >::operator-> (this=0xffff6c2c2ed0) at /usr/include/c++/15.2.1/optional:1165
#5  0x0000ffff883b4e58 in exportSurfaceHandle (context=0xffff6c05def0, surface_id=1, mem_type=1073741824, flags=5, descriptor=0xffff88ffd4f0) at ../src/surface.cc:291
--Type <RET> for more, q to quit, c to continue without paging--
#6  0x0000ffffaeb465b8 in vaExportSurfaceHandle () from /usr/lib/libva.so.2
...
```

which seems to relate to this issue?

**Comment by mxsrc** [comment]
> I try to get vaapi -> v4l2_request -> (hantro, rkvdec) -> rk3399 (pinebook-pro) to work. However, mpv SIGABRTs with
> 
> ```
> Thread 1 (Thread 0xffff88ffe520 (LWP 2410)):
> #0  0x0000ffffae92b1f4 in ?? () from /usr/lib/libc.so.6
> #1  0x0000ffffae8d78d8 in raise () from /usr/lib/libc.so.6
> #2  0x0000ffffae8c1c38 in abort () from /usr/lib/libc.so.6
> #3  0x0000ffffaa9937a8 in std::__glibcxx_assert_fail (file=<optimized out>, line=<optimized out>, function=<optimized out>, condition=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/assert_fail.cc:41
> #4  0x0000ffff883b6010 in std::optional<std::reference_wrapper<V4L2M2MDevice::Buffer const> >::operator-> (this=0xffff6c2c2ed0) at /usr/include/c++/15.2.1/optional:1165
> #5  0x0000ffff883b4e58 in exportSurfaceHandle (context=0xffff6c05def0, surface_id=1, mem_type=1073741824, flags=5, descriptor=0xffff88ffd4f0) at ../src/surface.cc:291
> --Type <RET> for more, q to quit, c to continue without paging--
> #6  0x0000ffffaeb465b8 in vaExportSurfaceHandle () from /usr/lib/libva.so.2
> ...
> ```
> 
> which seems to relate to this issue?


I was not able to look into this last year due to a new day job. My new year's resolution is to make some progress on this, so I might have a fix in some time.

**Comment by mxsrc** [comment]
> Hi, it's also empty with armbian in Amlogic s905x3, hk1box. How can I solve it?
> 
> ```
> armbian:libva-v4l2:% uname -a                                          <master>
> Linux armbian 6.1.157-ophub #1 SMP Mon Oct 20 10:19:24 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux
> 
> armbian:~:% neofetch
>         #####           yunsmall@armbian 
>        #######          ---------------- 
>        ##O#O##          OS: Armbian OS 25.11.0 noble aarch64 
>        #######          Host: HK1 Box/Vontar X3 
>      ###########        Kernel: 6.1.157-ophub 
>     #############       Uptime: 2 hours 
>    ###############      Packages: 1580 (dpkg) 
>    ################     Shell: zsh 5.9 
>   #################     Resolution: 720x576i 
> #####################   DE: GNOME 46.0 
> #####################   WM: Mutter 
>   #################     WM Theme: Adwaita 
>                         Theme: Yaru [GTK2/3] 
>                         Icons: Yaru [GTK2/3] 
>                         Terminal: gnome-terminal 
>                         CPU: ARMv8 rev 0 (v8l) (4) @ 2.100GHz 
>                         Memory: 2610MiB / 3776MiB 
> 
> armbian:libva-v4l2:% LIBVA_DRIVERS_PATH=./build/src LIBVA_DRIVER_NAME=v4l2 vainfo                                  
> libva info: VA-API version 1.20.0
> libva info: User environment variable requested driver 'v4l2'
> libva info: Trying to open ./build/src/v4l2_drv_video.so
> libva info: Found init function __vaDriverInit_1_20
> libva info: va_openDriver() returns 0
> vainfo: VA-API version: 1.20 (libva 2.12.0)
> vainfo: Driver version: v4l2
> vainfo: Supported profile and entrypoints
> 
> armbian:libva-v4l2:% v4l2-ctl --list-formats-ext --list-formats-out-ext -d /dev/video0 -D
> Driver Info:
> 	Driver name      : meson-vdec
> 	Card type        : Amlogic Video Decoder
> 	Bus info         : platform:meson-vdec
> 	Driver version   : 6.1.157
> 	Capabilities     : 0x84204000
> 		Video Memory-to-Memory Multiplanar
> 		Streaming
> 		Extended Pix Format
> 		Device Capabilities
> 	Device Caps      : 0x04204000
> 		Video Memory-to-Memory Multiplanar
> 		Streaming
> 		Extended Pix Format
> ioctl: VIDIOC_ENUM_FMT
> 	Type: Video Capture Multiplanar
> 
> 	[0]: 'NM12' (Y/UV 4:2:0 (N-C))
> ioctl: VIDIOC_ENUM_FMT
> 	Type: Video Output Multiplanar
> 
> 	[0]: 'VP90' (VP9, compressed, dyn-resolution)
> 		Size: Continuous 256x144 - 3840x2160
> 	[1]: 'HEVC' (HEVC, compressed, dyn-resolution)
> 		Size: Continuous 256x144 - 3840x2160
> 	[2]: 'H264' (H.264, compressed, dyn-resolution)
> 		Size: Continuous 256x144 - 3840x2160
> 	[3]: 'MPG1' (MPEG-1 ES, compressed)
> 		Size: Continuous 256x144 - 1920x1080
> 	[4]: 'MPG2' (MPEG-2 ES, compressed)
> 		Size: Continuous 256x144 - 1920x1080
> ```

This is acutally the very chip that made me look into this in the first place. Unfortunately, meson offers the stateful decoding interface only, which differs significantly enough to make implementation not straight forward. My plan is to get this working at some point but I wouldn't hold out on it.

**Comment by valpackett** [comment]
FWIW there is now a new experimental libva adapter for **stateful** v4l2: https://github.com/strongtz/libva-v4l2 At least for now though, only works with qcom-iris and with extra kernel patches. **Don't** expect any support right now, this is only FYI.
